// DO NOT EDIT THIS FILE! If you need changes, change the code generator
// instead. This file was generated by running the following command:
//
//    /home/ken/src/monad/util/ctypes/codegen/cg-ctypes -s
//    /home/ken/src/monad/libs/execution/ctypes rust -p monad-event-ring/src
//    -frustfmt +nightly

use crate::{event_metadata::*, exec_event_types::exec_event_type};

pub const EXEC_EVENT_METADATA: [EventMetadata; 12] = [
    EventMetadata {
        event_type: exec_event_type::NONE as u16,
        c_name: "NONE",
        description: "Reserved code so that 0 remains invalid",
    },
    EventMetadata {
        event_type: exec_event_type::BLOCK_START as u16,
        c_name: "BLOCK_START",
        description: "Event recorded at the start of block execution",
    },
    EventMetadata {
        event_type: exec_event_type::BLOCK_END as u16,
        c_name: "BLOCK_END",
        description: "Event recorded upon successful transaction execution",
    },
    EventMetadata {
        event_type: exec_event_type::BLOCK_VOTED as u16,
        c_name: "BLOCK_VOTED",
        description: "Event recorded when a proposed block obtains a quorum certificate",
    },
    EventMetadata {
        event_type: exec_event_type::BLOCK_FINALIZED as u16,
        c_name: "BLOCK_FINALIZED",
        description: "Event recorded when consensus finalizes a block",
    },
    EventMetadata {
        event_type: exec_event_type::BLOCK_VERIFIED as u16,
        c_name: "BLOCK_VERIFIED",
        description: "Event recorded when consensus verifies the state root of a finalized block",
    },
    EventMetadata {
        event_type: exec_event_type::BLOCK_REJECT as u16,
        c_name: "BLOCK_REJECT",
        description: "Event recorded when a block is rejected (i.e., is invalid)",
    },
    EventMetadata {
        event_type: exec_event_type::TXN_START as u16,
        c_name: "TXN_START",
        description: "Event recorded when transaction processing starts",
    },
    EventMetadata {
        event_type: exec_event_type::TXN_REJECT as u16,
        c_name: "TXN_REJECT",
        description: "Event recorded when a transaction is rejected (i.e., is invalid)",
    },
    EventMetadata {
        event_type: exec_event_type::TXN_LOG as u16,
        c_name: "TXN_LOG",
        description: "Event recorded when a transaction emits a LOG",
    },
    EventMetadata {
        event_type: exec_event_type::TXN_RECEIPT as u16,
        c_name: "TXN_RECEIPT",
        description: "Event recorded when transaction execution halts",
    },
    EventMetadata {
        event_type: exec_event_type::EVM_ERROR as u16,
        c_name: "EVM_ERROR",
        description: "Error occurred in execution process (not a validation error)",
    },
];

pub static EXEC_EVENT_DOMAIN_METADATA: EventDomainMetadata = EventDomainMetadata {
    metadata_hash: [
        0xe1, 0xa2, 0xd6, 0xdf, 0x3b, 0x40, 0x64, 0x86, 0x3d, 0xb2, 0x27, 0xf0, 0xf4, 0x56, 0xec,
        0x15, 0x2f, 0x8c, 0x54, 0x8d, 0xb, 0x1a, 0x11, 0xde, 0x68, 0xe3, 0x51, 0x83, 0x75, 0x18,
        0xd8, 0xe5,
    ],
    events: &EXEC_EVENT_METADATA,
};

pub const EXEC_EVENT_DEFAULT_RING_PATH: &str = "/dev/hugepages/monad-exec-events";
