[package]
name = "monad-keystore"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[[bin]]
name = "monad-keystore"
bench = false

[dependencies]
monad-bls = { workspace = true }
monad-crypto = { workspace = true }
monad-secp = { workspace = true }

aes = { workspace = true }
bip32 = { workspace = true }
clap = { workspace = true, features = ["derive"] }
ctr = { workspace = true }
hex = { workspace = true }
pbkdf2 = { workspace = true, features = ["simple"] }
rand = { workspace = true }
scrypt = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tiny-bip39 = { workspace = true }
unicode-normalization = { workspace = true }
zeroize = { workspace = true }
